### ISSUE TITLE
Choose to enable/disable Mollie payment options

### ISSUE THREAD

**Issue by theemstra** [dropcart/dropcart#100]
For ex. I'd like my customers to pay with iDeal, creditcard and SEPA-incasso only. When I set these options in Mollie all payment options are still offered in Dropcart

**Comment by MartijnOud** [comment]
We call the Mollie API to get all payment methods and only display the activated paymethods in `dc_shoppingcart3.php`: https://github.com/dropcart/dropcart/blob/master/dc_shoppingcart3.php#L313

On Mollie's own website  you can toggle the paymethods per website (or account wide):

![image](https://cloud.githubusercontent.com/assets/1292436/12777153/37fa3860-ca5b-11e5-9dc4-066040f54a3f.png)


Is this not working for you?

**Comment by theemstra** [comment]
Yeah sorry, got it!

Met vriendelijke groet,

Thom Heemstra
M: 0620074324
