### ISSUE TITLE
'Out of stock' items are €0,00

### ISSUE THREAD

**Issue by theemstra** [dropcart/dropcart#107]
They should be hidden or the right price should be showed.

**Comment by MartijnOud** [comment]
The stock and price are not related so this should not be possible. I've also tested this with multiple products (and versions) and cant replicate this:

![image](https://cloud.githubusercontent.com/assets/1292436/13254778/3a5d09c8-da43-11e5-8569-074a802f869e.png)

Can you give an example of the API call? This might be related to a specific product. You can leave out the API key and instead send your customerId.

**Comment by theemstra** [comment]
Martijn, do you have Skype? I can show you an example

**Comment by theemstra** [comment]
Hi Martijn,

Here is an example of the page:
![2](https://cloud.githubusercontent.com/assets/8525629/13361924/ee5eaf14-dcc1-11e5-8f7b-3250f149b8b3.PNG)
![1](https://cloud.githubusercontent.com/assets/8525629/13361923/ee5bb674-dcc1-11e5-91da-8989a40d6c1c.PNG)

**Comment by MartijnOud** [comment]
This isn't related to the stock (this example is in stock) but presumably you use `priceMSRP` for your price calculation. This product doesn't have a specific MSRP price and thus displays `0`. As a backup the `btn` is disabled so customers can't order a free product.
