### ISSUE TITLE
Beheer pagina not working

### ISSUE THREAD

**Issue by twentytrading** [dropcart/dropcart#114]
When i try to open beheer page, i get the following error.
![knipsel](https://cloud.githubusercontent.com/assets/18060208/14033890/5cae2e06-f21e-11e5-9e03-10bc27d2cb30.PNG)
Do i miss something?

**Comment by MartijnOud** [comment]
It looks like your `SITE_URL` is set incorrectly. Can you change the following and see if it works?

In the file `/includes/php/dc_config.php` find the line:

````PHP
define('SITE_URL', getSiteUrl()); // ends in a slash
````

Replace it with

````PHP
// define('SITE_URL', getSiteUrl()); // ends in a slash
define('SITE_URL', 'http://inktplaza.nl/inkt/'); // ends in a slash
````

**Comment by twentytrading** [comment]
Uw mail is ontvangen, wij zullen deze zo spoedig mogelijk beantwoorden.

Team TwentyTrading

**Comment by MartijnOud** [comment]
Almost :).

It should be:

````PHP
// define('SITE_URL', getSiteUrl()); // ends in a slash
define('SITE_URL', 'http://inktplaza.nl/inkt'); // ends in a slash
````

(without a trailing slash)

**Comment by MartijnOud** [comment]
Looks like that fixed it. It's an issue with our code which I will look into (#115). Let me know if you run into anything else by opening a new issue.
