### ISSUE TITLE
Product Manage: Display what prices are incl or excl VAT

### ISSUE THREAD

**Issue by MartijnOud** [dropcart/dropcart#55]
On `beheer/dc_product_manage` it should be better specified which prices are inclusive or exclusive VAT.

- Price (Purchase ex) = excl.
- Price (Inktweb.nl) = incl.
- Price (MSRP) = incl
- Price = incl

**Comment by Dmitrev** [comment]
Close?
![image](https://cloud.githubusercontent.com/assets/1260209/8571777/f1333bb0-2588-11e5-8f13-435d5512795d.png)

**Comment by MartijnOud** [comment]
That in the settings page. This should also be added to `beheer/dc_product_manage`.
