### ISSUE TITLE
Dropcart werkt niet out-of-the-box zonder vhost (enhancement)

### ISSUE THREAD

**Issue by Dmitrev** [dropcart/dropcart#57]
De dropcart installatie gaat er altijd vanuit dat alle bestanden in de root directory staan op de server. Dit maakt het lastiger om te werken op localhost.

Mijn installatie staat in ```/var/www/html/dropcart```
Dropcart probeert het config bestand te laden uit ```/var/www/html/includes/php/..```

Zie screenshot:
![http://i.imgur.com/04Lu5Ib.png](http://i.imgur.com/04Lu5Ib.png)

**Comment by MartijnOud** [comment]
Yeah dit klopt. Moet nog opgepakt worden (duplicate #29.)
